apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortly-delpp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shortly-delpp
  template:
    metadata:
      labels:
        app: shortly-delpp
    spec:
      containers:
      - name: shortly-delpp
        image: jaymath237/shortly:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          ports:
            - containerPort: 8080
          env:
          - name: shortly-delpp-username
            valueFrom: 
              secretKeyRef:
                name: shortly-delpp-secret
                key: username
          - name: shortly-delpp-password
            valueFrom:
              secretKeyRef:
                name: shortly-delpp-secret

